[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.mbstring", "php82Extensions.pdo_mysql", "nodejs-18_x", "php82Packages.composer"]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev",`
    "npm install", 
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"

]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"